# Generated by Django 4.2.15 on 2024-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth',
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
